### ISSUE TITLE
Unable to save from ZX Basic When Using Externa; VHD 

### ISSUE THREAD

**Issue by Bendzuk** [MiSTer-devel/ZXNext_MISTer#6] opened 2021-05-25 19:05 UTC
Trying to save any ZX Next BASIC program using something like save "example.bas", produces a message saying:
 
"Not ready 0:1".

Something does get saved to the VHD but seems to be corrupted and  it is not possible to load it back in again.
I am using an external USB drive to store the VHD, not sure if this is a factor.

There is a thread on the issue here: https://misterfpga.org/viewtopic.php?p=26328#p26328

Thanks

**Comment by sorgelig** [comment] 2021-05-26 20:32
There is already reported: https://github.com/MiSTer-devel/ZXNext_MISTer/issues/4 
As i've told there, i can't reproduce the issue. 
closing as duplicate. Continue in that issue.

**Closed by sorgelig** 2021-05-26 20:32 UTC

**Comment by jsanjose** [comment] 2023-01-04 20:23
This issue is not the same as issue #4.

Please read this forum topic: https://misterfpga.org/viewtopic.php?t=2645

As discussed in that topic, this issue should be reopened. The solution to that problem is discussed in the aforementioned forum topic: the fix is to revert commit [e7e7fd56](https://github.com/MiSTer-devel/ZXNext_MISTer/commit/e7e7fd56a3d67daf4883b69cdcbaa306373b7ae8).
